### ISSUE TITLE
[建议] 当数据不存在时返回 Status 404

### ISSUE THREAD

**Issue by Ukenn2112** [itorr/anitabi.cn-document#1]
- 我发现在调用 API 时当数据不存在时 Status 也是返回 200，虽说并没有返回任何信息，但是在程序上不太方便做判断，方便的话希望能够加上，谢谢。

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/60847880/229271885-8fa8d44b-b269-47a3-82dc-a9eb4b985414.png">

**Comment by itorr** [comment]
目前不存在作品会改为返回 404 了🤗

**Comment by Ukenn2112** [comment]
嗯嗯，已更新换上

https://github.com/Ukenn2112/BangumiTelegramBot/commit/d79eddba1ef498625d587120fd5ce0d917cd9fc2
